project 'LemonKit.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'LemonKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LemonKit

end

target 'LKSamples' do
  
  pod 'LemonBubble'

  target 'LKSamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LKSamplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
